name: Development Release
on:
  pull_request:
    branches:
      - master
jobs:
  Build:
    name: Build, test and release to development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        run: ./gradlew buildZip
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Deploy Storage to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: bloom-services-artifacts
          template: .cloudformation/artifact-store.yaml
          no-fail-on-empty-changeset: '1'
      - name: Upload Artifacts
        run: aws s3 sync build/artifacts s3://bloom-services-artifacts
      - name: Calculate deployment artifact versions
        run: |
          echo "LAMBDA_HEALTH_VERSION=$(./gradlew -q :bloom-health:printVersion)" >> $GITHUB_ENV
          echo "LAMBDA_SAVINGS_ADD_VERSION=$(./gradlew -q :bloom-savings-add:printVersion)" >> $GITHUB_ENV
          echo "LAMBDA_SAVINGS_DELETE_VERSION=$(./gradlew -q :bloom-savings-delete:printVersion)" >> $GITHUB_ENV
          echo "LAMBDA_SAVINGS_LIST_VERSION=$(./gradlew -q :bloom-savings-list:printVersion)" >> $GITHUB_ENV
          echo "LAMBDA_SAVINGS_UPDATE_VERSION=$(./gradlew -q :bloom-savings-update:printVersion)" >> $GITHUB_ENV
      - name: Deploy Stack to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: dev-bloom-services
          template: .cloudformation/stack.yaml
          parameter-overrides: 'Environment=dev,CertificateArn=${{ secrets.CERTIFICATE_ARN }},LambdaHealthVersion=${{ env.LAMBDA_HEALTH_VERSION }},LambdaSavingsAddVersion=${{ env.LAMBDA_SAVINGS_ADD_VERSION }},LambdaSavingsDeleteVersion=${{ env.LAMBDA_SAVINGS_DELETE_VERSION }},LambdaSavingsListVersion=${{ env.LAMBDA_SAVINGS_LIST_VERSION }},LambdaSavingsUpdateVersion=${{ env.LAMBDA_SAVINGS_UPDATE_VERSION }}'
          no-fail-on-empty-changeset: '1'
      - name: Deploy API Gateway
        run: aws apigateway create-deployment --rest-api-id blhrk2bec9 --stage-name dev
